version: '3.9'
services:
  cassandra-seed:
    image: cassandra:4.0.7
    container_name: cassandra-seed
    hostname: cassandra-seed
    networks:
      - cassandra-network
    ports:
      - 9042:9042
    healthcheck:
      interval: 15s
      timeout: 10s
      retries: 20
      test: ["CMD", "cqlsh", "-e describe keyspaces"]
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=datacenter1

  cassandra-initializer:
    image: cassandra:4.0.7
    container_name: cassandra-initializer
    networks:
      - cassandra-network
    depends_on:
      cassandra-seed:
        condition: service_healthy
      cassandra-node:
        condition: service_healthy
    volumes:
      - ./keyspace.cql:/opt/keyspace.cql
    command: cqlsh cassandra-seed -f /opt/keyspace.cql

  cassandra-node:
    image: cassandra:4.0.7
    scale: 2
    healthcheck:
      interval: 15s
      timeout: 10s
      retries: 50
      test: ["CMD", "cqlsh", "-e describe keyspaces"]
    depends_on:
      - cassandra-seed
    networks:
      - cassandra-network
    environment:
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=datacenter1

  spring-app-instance:
    build:
      context: .
      dockerfile: Dockerfile
    scale: 3
    networks:
      - cassandra-network
    depends_on:
      cassandra-seed:
        condition: service_healthy
      cassandra-node:
        condition: service_healthy
    stdin_open: true
    tty: true

networks:
  cassandra-network:
    driver: bridge
